study_name: scovmod
output_prefix: scovmod_tree

transmission_tree:
  infection_history_file: InfectedIndividuals.1.csv
  transmission_events_file: TransmissionEvents.1.csv
  target_component_size: 1000
