study_name: boston

inputs:
  metadata: data/processed/boston/boston_metadata.parquet
  pairwise_distances: data/processed/boston/boston_pairwise_distances.parquet
  id_col_1: SeqID1
  id_col_2: SeqID2
  date_col: Date
  exposure_col: Exposure
  temporal_col: Temporal_Distance
  genetic_col: SNP_Distance

inference:
  included_intermediate_counts: [0]

analysis:
  resolution: 0.3
  min_cluster_size: 2
  focus_exposures: [Conference, SNF]
